### ISSUE TITLE
Pinterest Support?

### ISSUE THREAD

**Issue by searchy2** [ahmed-adel-said/socialmediasignup#1]
Great library, look forward to contributing. 

Any plans to support Pinterest? 

A quick question, why does LinkedIn require a whole bunch of files AND the app to be installed in order to sign in? 

Thanks for sharing, will be very useful!

**Comment by ahmed-adel-said** [comment]
Hello Ray,

So happy that the library meets your expectations!

About Pinterest, I didn't use it in the apps I am working on it, so I didn't a lot about how to integrate it or if there is a sdk for the platform but promise it will be available in the next version ✋ .

And if you want to make it please feel free to contribute and make an enhancement in the library to be able to make any developer integrate with Pinterest so easy via SocialMediaSignUp Library 💯.

Regarding the LinkedIn, what I really did in this point is talking the open source LinkedIn sdk and put it as is in the library to make it simple to the integrated app and to be able in the future if we want to enhance the library to do something more than sign up and retrieving the data. But, what I think about is a smart idea to make the integration process more easier than now because a lot of people told me that if I want to integrate with one of the five existing platforms not all of them, what can I do ?

So, If you have a smart idea about isolate the five platform from each others to be every one a separate component to make the integration process easier, please contribute and take its credits 😺 

Thanks a lot really it's totally appreciated 👍

**Comment by searchy2** [comment]
Hi Ahmed,

You've built a really solid framework to improve upon. :bridge_at_night: 

The question about the LinkedIn integration was why it was separate files instead of an SDK. I think I understand the reasoning behind that. So a followup question, why doesn't the LinkedIn SDK have a website redirect backup? It only works if the user has the app installed correct?

What do you think about caching the request token in SavedPrefs and exposing that to the developer? That would allow developers to call GraphRequests and other APIs to fetch custom information. 

I think breaking up the platforms is necessary and needs to be done early so future development doesn't have to be reworked. These social SDKs are not lightweight at all. 

Unfortunately, I'm at a loss for an elegant solution. I would create a separate repo for each social integration and have the main repo contain the common code such as SocialMediaSignUpActivity. Each social repo would depend upon the main repo. This is not the most elegant solution but it would remove the need to import unused SDKs.

I do hope the way I suggest is not the only way. My way is easy enough and the end result is easy for developers. Would be messy for this repo though. I guess it really depends on if you wish for this repo to be a social media signup manager or only useful for apps that are going to use all 5 social networks. 

Look forward to your thoughts :thought_balloon:

**Comment by searchy2** [comment]
Closing this issue for now.
